# Generated by Django 4.2.7 on 2023-11-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_type', models.CharField(max_length=50)),
                ('table_capacity', models.IntegerField()),
                ('Indoor_or_Outdoor', models.CharField(max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='seating',
        ),
        migrations.DeleteModel(
            name='Seating',
        ),
    ]
