# Generated by Django 4.2.7 on 2023-11-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_seat_remove_restaurant_seating_delete_seating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='seats',
            field=models.ManyToManyField(to='main_app.seat'),
        ),
    ]
