# Generated by Django 4.2.7 on 2023-11-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_restaurant_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='Indoor_or_Outdoor',
            new_name='indoor_or_outdoor',
        ),
    ]
