# Generated by Django 4.2.7 on 2023-11-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_meal_had'),
        ('main_app', '0002_mealphoto'),
        ('main_app', '0005_remove_comment_upvotes'),
    ]

    operations = [
    ]
