# Generated by Django 4.2.7 on 2023-11-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20231128_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('indoor', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('indoor_outdoor', 'Indoor & Outdoor')], max_length=20)),
                ('handicap', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='meal_had',
            options={},
        ),
        migrations.RenameField(
            model_name='mealphoto',
            old_name='restaurant',
            new_name='meal_had',
        ),
    ]
