# Generated by Django 4.2.7 on 2023-11-29 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_seating_alter_meal_had_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_had',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='seating',
            field=models.ManyToManyField(to='main_app.seating'),
        ),
        migrations.AlterField(
            model_name='mealphoto',
            name='meal_had',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.meal_had'),
        ),
    ]
