# Generated by Django 4.2.7 on 2023-11-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20231128_1605'),
        ('main_app', '0007_seating_alter_meal_had_options_and_more'),
    ]

    operations = [
    ]
