# Generated by Django 4.2.7 on 2023-11-28 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_merge_20231128_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='seating',
            field=models.ManyToManyField(to='main_app.seating'),
        ),
        migrations.AlterField(
            model_name='mealphoto',
            name='meal_had',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.meal_had'),
        ),
    ]
