# Generated by Django 4.2.7 on 2023-11-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_meal_had_image_url_restaurant_seating_and_more'),
        ('main_app', '0009_restaurant_seating_alter_mealphoto_meal_had'),
    ]

    operations = [
    ]
