# Generated by Django 4.2.7 on 2023-11-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merge_20231129_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal_had',
            name='image_url',
        ),
    ]
