# Generated by Django 4.2.7 on 2023-11-29 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_meal_had_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealphoto',
            name='meal_had',
        ),
        migrations.AddField(
            model_name='mealphoto',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.restaurant'),
            preserve_default=False,
        ),
    ]
